export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const LOAD_FLIGHTS_SUCCESS = "LOAD_FLIGHTS_SUCCESS";
export const LOAD_PASSENGERS_SUCCESS = "LOAD_PASSENGERS_SUCCESS";
